apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggenerator
  template:
    metadata:
      labels:
        app: loggenerator
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: log-generator
          image: rahul004x/log-generator:v1
          volumeMounts:
            - name: shared-logs
              mountPath: /shared
        - name: log-reader
          image: rahul004x/log-reader:v1
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
          volumeMounts:
            - name: shared-logs
              mountPath: /shared